# Generated by Django 5.0 on 2024-01-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
