# Generated by Django 5.0 on 2024-01-25 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_rename_is_staff_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task_manager.user', verbose_name='пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priority',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='task_manager.user', verbose_name='пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='task_manager.user', verbose_name='пользователь'),
        ),
    ]
