# Generated by Django 5.0 on 2024-01-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_category_user_priority_user_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='user_id',
        ),
    ]
