# Generated by Django 5.0 on 2024-01-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0009_rename_user_category_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_id',
        ),
    ]
